live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
dynamic_padding = true

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12

[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[colors.normal]
black   = "#000000"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[keyboard]
bindings = [
    { key = "c", mods = "Control|Shift", action = "Copy" },
    { key = "v", mods = "Control|Shift", action = "Paste" },
    { key = "=", mods = "Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
    { key = "0", mods = "Control", action = "ResetFontSize" },
    { key = "F11", action = "ToggleFullscreen" },
]
