#!/bin/sh

bspc monitor --reset-desktops I II III IV V VI VII VIII IX

bspc config border_width 2
bspc config window_gap 5

bspc config focused_border_color "#D79921"

nitrogen --restore &
/usr/local/bin/picom &
/usr/local/bin/battery &
fcitx5 &
redshift -l 21.033333:105.849998 &
xbanish &
dunst &
nm-applet &
sxhkd &
xsetroot -cursor_name left_ptr &
polybar &
