#!/usr/bin/env sh

help() {
  echo "Usage: ./brightness --card [NAME] [OPTION]"
  echo -e "--card\t\tName card"
  echo -e "--get\t\tGet backlight"
  echo -e "--inc\t\tIncrease backlight +5"
  echo -e "--dec\t\tDecrease backlight +5"
}

if [[ $# -ne 3 ]]; then
  help
  exit 1
fi

if [[ "$1" == "--card" ]]; then
  card=$2
else
  help
  exit 1
fi

get_backlight() {
  echo -n `cat /sys/class/backlight/$card/brightness`
}

percent_backlight() {
  echo -n `expr $(get_backlight) / 10`
}

get_icon() {
  perc=$(perccent_backlight)

	if [[ ($perc -ge 0) && ($perc -le 35) ]]; then
		echo -n "brightness-low-symbolic"
	elif [[ ($perc -ge 35) && ($perc -le 70) ]]; then
		echo -n "brightness-medium-symbolic"
	elif [[ ($perc -ge 70) && ($perc -le 100) ]]; then
		echo -n "brightness-high-symbolic"
	fi
}

notify_cmd() {
  title="Brightness"
  message=$(percent_backlight)%
  progress=$(percent_backlight)%
  icon=$(get_icon)
  id=0x62

  dunstify --urgency normal $title $message --hints int:value:$progress --icon=$icon --replace=$id
}

inc_backlight() {
  echo -n `expr $(get_backlight) + 50` > /sys/class/backlight/$card/brightness
  paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga
}

dec_backlight() {
  echo -n `expr $(get_backlight) - 50` > /sys/class/backlight/$card/brightness
  paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga
}

if [[ "$3" == "--get" ]]; then
  percent_backlight
elif [[ "$3" == "--inc" ]]; then
  inc_backlight
  notify_cmd
elif [[ "$3" == "--dec" ]]; then
  dec_backlight
  notify_cmd
else
  help
  exit 1
fi

