#!/usr/bin/env sh

get_volume() {
  echo -n `pamixer --get-volume`
}

get_muted() {
  echo -n `pamixer --get-mute`
}

get_icon() {
	volume=$(get_volume)
  muted=$(get_muted)

  if [[ $muted == "true" ]]; then
    echo "audio-volume-muted"
    return
	elif [[ ($volume -ge 0) && ($volume -le 30) ]]; then
    echo "audio-volume-low"
    return
	elif [[ ($volume -ge 30) && ($volume -le 60) ]]; then
    echo "audio-volume-medium"
    return
	elif [[ ($volume -ge 60) && ($volume -le 100) ]]; then
    echo "audio-volume-high"
    return
	fi
}

notify_cmd() {
  title="Volume"
  muted=$(get_muted)

  if [[ $# -ne 1 ]]; then
    message=$(get_volume)%
  else
    message=$1
  fi

  progress=$(get_volume)
  icon=$(get_icon)
  id=0x76

  if [[ $muted == "true" ]]; then
    dunstify --urgency normal $title $message --icon=$icon --replace=$id
  else
    dunstify --urgency normal $title $message --hints int:value:$progress --icon=$icon --replace=$id
  fi
}

inc_volume() {
  muted=$(get_muted)

  if [[ $muted == "true" ]]; then
    pamixer --toggle-mute
  fi

	pamixer --increase 5
  notify_cmd
  paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
}

dec_volume() {
  muted=$(get_muted)

  if [[ $muted == "true" ]]; then
    pamixer --toggle-mute
  fi

	pamixer --decrease 5
  notify_cmd
  paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
}

toggle_mute() {
  muted=$(get_muted)

	if [[ $muted == "true" ]]; then
		pamixer --toggle-mute
    notify_cmd
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
	else
		pamixer --toggle-mute
    notify_cmd "Mute"
	fi
}

help() {
  echo "Usage: ./volume [OPTION]"
  echo -e "--get\t\tGet volume"
  echo -e "--inc\t\tIncrease volume +5"
  echo -e "--dec\t\tDecrease volume +5"
  echo -e "--toggle\tToggle mute"
}

if [[ $# -ne 1 ]]; then
  help
  exit 1
fi

if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
elif [[ "$1" == "--help" ]]; then
  help
  exit 1
else
  help
  exit 1
fi
